steps:
- id: pull dependencies
  name: bitwalker/alpine-elixir-phoenix:1.6.6
  args: ["mix", "do", "deps.get", "--all", ",", "compile"]
  waitFor: ["-"]
- id: start test database
  name: postgres:9.6-alpine
  args: ["postgres", "2>&1", "&"]
  waitFor: ["-"]
- id: run tests
  name: bitwalker/alpine-elixir-phoenix:1.6.6
  args: ['mix', 'test', '--trace', '--cover']
  waitFor: ["start test database", "pull dependencies"]
- id: static code analysis
  name: bitwalker/alpine-elixir-phoenix:1.6.6
  args: ['mix', 'credo', '--verbose']
  waitFor: ["pull dependencies"]
- id: docker build
  name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.']
images:
- gcr.io/$PROJECT_ID/quickstart-image
